[bumpver]
current_version = "2.6"
version_pattern = "MAJOR.MINOR"
# commit_message = "bump version {old_version} -> {new_version}"
# tag_message = "{new_version}"
# tag_scope = "default"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"pyproject.toml" = ['version = "{version}"']
"src/LogseqMarkdownParser/__init__.py" = ['__VERSION__: str = "{version}"']
