[bumpver]
current_version = "2.8"
version_pattern = "MAJOR.MINOR"
# commit_message = "bump version {old_version} -> {new_version}"
# tag_message = "{new_version}"
# tag_scope = "default"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"setup.py" = ['version="{version}",']
"src/LogseqMarkdownParser/classes.py" = ['__VERSION__: str = "{version}"']
